// lessons.js — m7 の COBOL 例題(ab-147)。すまが 2026-08-06 に作った6問の流れ(DISPLAY・MOVE・PIC 9・IF・PERFORM・ADD)に、
// ab-147 の「残り2」にあった PERFORM VARYING と ACCEPT を足した8問(2026-10-09 礼文)。
// 1問は { id, title, point(何を覚える問いか), code(固定形式、8桁目から), input(ACCEPT に渡す行), ask, choices, answer(choices の番号),
//          hint, lines: [[コードの行番号, 解説]] }。
// 正解(choices[answer])は、cobol.js で code を動かした出力を「/」でつないだものと同じでなければならない(lessons.test.mjs が見る)。

const head = (id) => [
  "       IDENTIFICATION DIVISION.",
  `       PROGRAM-ID. ${id}.`,
];

export const LESSONS = [
  {
    id: "display",
    title: "画面に出す: DISPLAY",
    point: "DISPLAY のあとに書いたものが、そのまま1行で出ます。文字は \" \" でかこみます。",
    code: [
      ...head("HELLO"),
      "       PROCEDURE DIVISION.",
      "           DISPLAY \"HELLO, COBOL\".",
      "           STOP RUN.",
    ],
    ask: "このプログラムを動かすと、何が出るでしょう。",
    choices: ["HELLO, COBOL", "\"HELLO, COBOL\"", "DISPLAY HELLO, COBOL", "何も出ない"],
    answer: 0,
    hint: "\" \" は「ここからここまでが文字」という印で、印そのものは出ません。",
    lines: [
      [1, "見出しの部(IDENTIFICATION DIVISION)。プログラムの名前を書くところ。"],
      [2, "PROGRAM-ID がプログラムの名前。ここでは HELLO。"],
      [3, "手順の部(PROCEDURE DIVISION)。ここから下が、実際に動く命令。"],
      [4, "DISPLAY で \" \" の中の文字を画面に出す。文の終わりにはピリオド。"],
      [5, "STOP RUN でプログラムを終える。"],
    ],
  },
  {
    id: "move-x",
    title: "入れる: MOVE(文字の箱)",
    point: "PIC X(5) は「文字が5つ入る箱」。短い文字を入れると、左に寄せて右を空白でうめます。長いと右がはみ出して切れます。",
    code: [
      ...head("MOVEX"),
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01  WS-NAME   PIC X(5).",
      "       PROCEDURE DIVISION.",
      "           MOVE \"SAKURA\" TO WS-NAME.",
      "           DISPLAY \"[\" WS-NAME \"]\".",
      "           MOVE \"UME\" TO WS-NAME.",
      "           DISPLAY \"[\" WS-NAME \"]\".",
      "           STOP RUN.",
    ],
    ask: "[ ] の中に何が出るでしょう(2行)。",
    choices: ["[SAKUR] / [UME  ]", "[SAKURA] / [UME]", "[AKURA] / [  UME]", "[SAKUR] / [UMEUR]"],
    answer: 0,
    hint: "箱は5文字ぶん。SAKURA は6文字です。2回目の MOVE は前の中身を全部入れかえます。",
    lines: [
      [3, "データの部(DATA DIVISION)。使う箱をここで決める。"],
      [4, "WORKING-STORAGE SECTION は、プログラムが動く間ずっとある作業用の箱の置き場。"],
      [5, "01 は箱の番号(いちばん上の段)。WS-NAME という名前で、PIC X(5) = 文字5つぶん。"],
      [7, "SAKURA(6文字)を5文字の箱へ。右の1文字(A)がはみ出して切れる。"],
      [8, "[ と ] ではさんで出すと、空白も目で見える。"],
      [9, "UME(3文字)を入れると、左に寄せて、のこり2文字は空白。前の SAKUR は消える。"],
    ],
  },
  {
    id: "pic9",
    title: "数の箱: PIC 9",
    point: "PIC 9(4) は「数字が4けた入る箱」。DISPLAY すると、足りないけたを左に 0 でうめて出します。",
    code: [
      ...head("PIC9"),
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01  WS-COUNT  PIC 9(4) VALUE 42.",
      "       PROCEDURE DIVISION.",
      "           DISPLAY WS-COUNT.",
      "           STOP RUN.",
    ],
    ask: "何が出るでしょう。",
    choices: ["0042", "42", "4200", "  42"],
    answer: 0,
    hint: "数の箱は、文字の箱と逆で、右に寄せて左を 0 でうめます。",
    lines: [
      [5, "PIC 9(4) は数字4けた。VALUE 42 で、はじめから 42 を入れておく。"],
      [7, "DISPLAY で数の箱を出すと、4けたぶん 0 でうめた形になる。"],
    ],
  },
  {
    id: "if",
    title: "分かれ道: IF / ELSE / END-IF",
    point: "IF のあとの条件が成り立てば上、成り立たなければ ELSE の下を動かします。END-IF で分かれ道がおしまい。",
    code: [
      ...head("IFELSE"),
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01  WS-SCORE  PIC 9(3) VALUE 75.",
      "       PROCEDURE DIVISION.",
      "           IF WS-SCORE >= 80",
      "               DISPLAY \"GREAT\"",
      "           ELSE",
      "               DISPLAY \"GOOD\"",
      "           END-IF.",
      "           STOP RUN.",
    ],
    ask: "何が出るでしょう。",
    choices: ["GOOD", "GREAT", "GREAT / GOOD", "何も出ない"],
    answer: 0,
    hint: "75 は 80 以上でしょうか。",
    lines: [
      [5, "点数の箱。はじめは 75。"],
      [7, "WS-SCORE が 80 以上なら、すぐ下の行へ。>= は「以上」。"],
      [8, "80 以上のときだけ動く。"],
      [9, "ELSE から下は、条件が成り立たなかったとき。"],
      [10, "75 なのでこちらが動く。"],
      [11, "END-IF で分かれ道がおわり。ピリオドで文もおわり。"],
    ],
  },
  {
    id: "perform-times",
    title: "くり返す: PERFORM 回数 TIMES",
    point: "PERFORM 3 TIMES から END-PERFORM までを、3回くり返します。",
    code: [
      ...head("TIMES"),
      "       PROCEDURE DIVISION.",
      "           PERFORM 3 TIMES",
      "               DISPLAY \"OK\"",
      "           END-PERFORM.",
      "           DISPLAY \"END\".",
      "           STOP RUN.",
    ],
    ask: "何が出るでしょう。",
    choices: ["OK / OK / OK / END", "OK / END / OK / END / OK / END", "OK / END", "OKOKOK / END"],
    answer: 0,
    hint: "くり返すのは END-PERFORM の上まで。DISPLAY は1回ごとに改行します。",
    lines: [
      [4, "ここから END-PERFORM までを3回。"],
      [5, "くり返しの中身。1回ごとに1行出る。"],
      [6, "くり返しのおわり。"],
      [7, "くり返しが終わってから1回だけ動く。"],
    ],
  },
  {
    id: "add",
    title: "足し算: ADD … TO",
    point: "ADD A TO B は「B に A を足して、B に入れなおす」。答えは TO のうしろの箱に入ります。",
    code: [
      ...head("ADDTO"),
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01  WS-TOTAL  PIC 9(3) VALUE 100.",
      "       01  WS-PRICE  PIC 9(3) VALUE 250.",
      "       PROCEDURE DIVISION.",
      "           ADD WS-PRICE TO WS-TOTAL.",
      "           ADD 30 TO WS-TOTAL.",
      "           DISPLAY WS-TOTAL.",
      "           DISPLAY WS-PRICE.",
      "           STOP RUN.",
    ],
    ask: "何が出るでしょう(2行)。",
    choices: ["380 / 250", "380 / 380", "350 / 280", "100 / 250"],
    answer: 0,
    hint: "変わるのは TO のうしろの WS-TOTAL だけ。WS-PRICE はそのままです。",
    lines: [
      [5, "合計の箱。はじめは 100。"],
      [6, "値段の箱。250。"],
      [8, "WS-TOTAL に WS-PRICE を足す → 350。WS-PRICE は変わらない。"],
      [9, "さらに 30 足す → 380。"],
      [10, "380(3けたなので 0 うめは無し)。"],
      [11, "250 のまま。"],
    ],
  },
  {
    id: "varying",
    title: "数えながらくり返す: PERFORM VARYING",
    point: "PERFORM VARYING I FROM 1 BY 1 UNTIL I > 3 は、I を 1 から 1 ずつ増やし、I が 3 をこえたら止めます。",
    code: [
      ...head("VARYING"),
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01  I         PIC 9(2).",
      "       01  WS-SUM    PIC 9(3) VALUE 0.",
      "       PROCEDURE DIVISION.",
      "           PERFORM VARYING I FROM 1 BY 1 UNTIL I > 3",
      "               ADD I TO WS-SUM",
      "           END-PERFORM.",
      "           DISPLAY \"SUM=\" WS-SUM.",
      "           STOP RUN.",
    ],
    ask: "何が出るでしょう。",
    choices: ["SUM=006", "SUM=003", "SUM=010", "SUM=6"],
    answer: 0,
    hint: "I は 1・2・3 と変わり、4 になったところで止まります。足した合計は? 箱は3けたです。",
    lines: [
      [5, "数える役の箱 I(2けた)。"],
      [6, "合計の箱。0 からはじめる。"],
      [8, "I を 1 にして、I > 3 になるまで、1 ずつ増やしながらくり返す。"],
      [9, "毎回、I を合計に足す(1+2+3)。"],
      [10, "くり返しのおわり。"],
      [11, "SUM= のうしろに合計を3けたで出す。"],
    ],
  },
  {
    id: "accept",
    title: "読みこむ: ACCEPT",
    point: "ACCEPT は、外から1行読んで箱に入れます。このページでは「入力」の欄に書いた行を、上から順に読みます。",
    code: [
      ...head("ACCEPT1"),
      "       DATA DIVISION.",
      "       WORKING-STORAGE SECTION.",
      "       01  WS-NAME   PIC X(6).",
      "       01  WS-AGE    PIC 9(3).",
      "       PROCEDURE DIVISION.",
      "           ACCEPT WS-NAME.",
      "           ACCEPT WS-AGE.",
      "           DISPLAY WS-NAME \"(\" WS-AGE \")\".",
      "           STOP RUN.",
    ],
    input: ["TARO", "7"],
    ask: "入力が「TARO」「7」の2行のとき、何が出るでしょう。",
    choices: ["TARO  (007)", "TARO(7)", "TARO(007)", "TARO  (7  )"],
    answer: 0,
    hint: "名前の箱は6文字、年の箱は数字3けた。文字の箱と数の箱で、うめ方が逆でした。",
    lines: [
      [5, "名前の箱。文字6つぶん。"],
      [6, "年の箱。数字3けた。"],
      [8, "1行目の入力(TARO)を読む。6文字の箱なので、うしろに空白が2つ。"],
      [9, "2行目の入力(7)を読む。数の箱なので 007。"],
      [10, "つなげて1行で出す。"],
    ],
  },
];

// 例題の画面で、出力を1行で見せるときのつなぎ方(選択肢と同じ形)
export const joinOutput = (lines) => lines.join(" / ");
